---
- name: Deploy Traefik with Helmfile
  command: helmfile apply
  args:
    chdir: "{{ playbook_dir }}/../k8s/helm/traefik"

- name: Apply middlewares
  command: kubectl apply -f middlewares/strip-prefix.yaml
  args:
    chdir: "{{ playbook_dir }}/../k8s/helm/traefik"