repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: mysql
    namespace: mysql
    createNamespace: true
    chart: bitnami/mysql
    values:
      - values.yaml # Optional: Create a values.yaml file for customizations
     